quarkus.log.level=INFO
#quarkus.log.min-level=TRACE
#quarkus.log.category."org.hibernate.SQL".level=DEBUG
#
#quarkus.vertx.event-loops-pool-size=8
#
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
#
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.jdbc.max-size=200
quarkus.datasource.jdbc.acquisition-timeout=10S
#
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.packages=m4gshm.benchmark.rest.java.storage.model.jpa
#
quarkus.native.enable-vm-inspection=true
#
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui