logging:
  level:
    root: INFO
#    org.apache.coyote.http11: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
springdoc:
  swagger-ui:
    path: /swagger-ui
spring:
  jpa:
    generate-ddl: true
  datasource:
    hikari:
      maximum-pool-size: 100
      max-lifetime: 120000
      min-idle: 0
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
server:
  tomcat:
    threads:
      max: 200
