logging:
  level:
    root: INFO
#    org.apache.coyote.http11: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui
spring:
  jpa:
    generate-ddl: true
  datasource:
    hikari:
      maximum-pool-size: 100
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
server:
  tomcat:
    threads:
      max: 200
