logging:
  level:
    root: INFO
#    org.apache.coyote.http11: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  jpa:
    generate-ddl: true
  datasource:
#    enabled: true
#    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

rest-controller: router