logging:
  level:
    root: INFO
#    io.r2dbc.postgresql.QUERY: DEBUG # for queries
#    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  jpa:
    generate-ddl: true
#  datasource:
#    hikari:
#      maximum-pool-size: 400
#    url: jdbc:postgresql://localhost:5433/postgres
#    username: postgres
#    password: postgres
  r2dbc:
    initialization-mode: always
    url: r2dbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    pool:
      max-size: 100
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

rest-controller: router