logging:
  level:
    root: INFO
springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  jpa:
    generate-ddl: true
  datasource:
    hikari:
      maximum-pool-size: 100
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

rest-controller: router