logging:
  level:
    root: INFO
#    org.apache.coyote.http11: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

rest-controller: router